name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "CONNECTED"

            # load environment properly
            source ~/.bashrc || true

            # go to project
            cd /home/ubuntu/CI-CD-Automation || exit

            # debug
            pwd
            ls -la

            # fix docker permission
            sudo usermod -aG docker ubuntu || true

            # run deploy
            chmod +x deploy.sh
            sudo bash deploy.sh
